[package]
name = "hor"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
hvm-core = { git = "https://github.com/HigherOrderCO/hvm-core" }
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
